# 项目启动端口配置
server:
  name: data_service
  address: localhost:8090
  # gin debug mode
  mode: debug

# OSS
oss:
  # OSS文件存储根地址
  storage-root: /tmp
  # OSS文件存储index
  storage-index: /file/


# RabbitMQ
rabbitmq:
  host: localhost
  port: 5672
  username: oss_start_admin
  password: 123456
  vhost: oss_start_vhost









